#!/usr/bin/env node --harmony
'use strict';

var Nodeunit = require('nodeunit');
var glob = require('glob');
var tests = glob.sync('test/*.js');

Nodeunit.reporters.default.run(tests, null, function (error) {
    process.exit( +!!error );
});
