#!/usr/bin/env node
'use strict';

var Nodeunit = require('nodeunit');

var child = require('child_process');
var glob = require('glob');

var tests = glob.sync('test/*.js');

function supports () {
    var version = process.version.split('.');

    return +version[1] > 10 && +version[2] > 2;
}

Nodeunit.reporters.default.run(tests, null, function (error) {

    if ( error ) {
        process.exit(1);

        return;
    }

//    if ( supports() ) {
//
//        child.exec('tools/test-harmony', function (err, so, se) {
//            console.log(so);
//            console.error(se);
//            process.exit( +!!err );
//        });
//
//        return;
//    }

    process.exit(0);

});
