#!/usr/bin/env node
'use strict';

var Fs = require('fs');
var Nodeunit = require('nodeunit');
var Path = require('path');
var tests = Fs.readdirSync('test');

tests = tests.map(function (fileName) {

    return Path.join('test', fileName);
}).filter(function (fileName) {

    return Fs.statSync(fileName).isFile();
});

Nodeunit.reporters.default.run(tests, null, function (error) {
    process.exit( +!!error );
});
